### ISSUE TITLE
Invisible water

### ISSUE THREAD

**Issue by MCPGNZ** [Moonlit-Games/Ultimate-Water-System#1]
The physics works correctly affecting other objects, but the water is invisible.

- reimport does not solve the issue

**unity version:** 2017.2.0f3
**uws version:** 1.0.0 
**spec:** Nvidia Optimus, Intel HD 4600, Geforce GTX 860M
**issue by:** [@vortexilation](https://forum.unity.com/threads/ultimate-water-system-the-most-advanced-realtime-water-simulation.493984/page-4#post-3253206)

**Comment by MCPGNZ** [comment]
I have some further question that could help me solve the issue:

* are there any runtime or compilation problems (errors, strange warnings, etc)
* did you run demo scenes, or created a new one?
* did you try to change Water Camera - Render Mode?
* does changing Rendering Path to Deferred (via Edit->Project Settings->Player->Other Settings) helps?
* is it possible to try to replicate this on another Unity version? (I'm aware that it shouldn't be unity-related problem as the others do not experience this issue, but it's a possibility that your hardware spec along with specific Unity version can cause problems)

**Comment by trippleflux** [comment]
Hello,
    It seems that inconsistency in line ending on one of the compute shader causing it or re-clicked the compute shader in the inspector are seems fixed it, i am just finished re-installing my windows, still waiting for Unity 2017.2.0p1 to be out for re-testing these workaround. 

It's quite weird if Unity Compiler is reading the sources by platform dependent read, as the warning by unity it's only affecting readability and debugging problems. 

Hopefully before the friday the unity patch will be released, and i could ping you back about the real causes.

**Comment by MCPGNZ** [comment]
Hi @trippleflux 

Is this still a problem after an update to the newest Unity version?

**Comment by trippleflux** [comment]
Hey @MCPGNZ ,
Sorry for very late reply, already tried with Unity 2017.2.0p2 with UWS 1.01 and hotfix b3, the problems seem resolved!, kudos and bravos for that, also much more fps increase (almost double, before it was around 60-80 fps, now it can reaches 100 fps to 130 fps!).

I think you can close this issue, thanks a lot btw.

**Comment by MCPGNZ** [comment]
Glad to hear that!
I'm closing the issue.
