### ISSUE TITLE
Dark shadow - flashlight effect

### ISSUE THREAD

**Issue by SemihParlayan** [Moonlit-Games/Ultimate-Water-System#11]
Hello! I'm having troubles after upgrading from PWW to UWS. I'm having a wierd shadow effect at the edges of my screen that look like a flashlight, this effect was not present in PWW. I think it has something to do with Planar Reflection. When the planar reflection intensity is set to 0 there is black shadows everywhere, when the instensity is increased the flashlight effect occurs and it looks good in the middle of the screen but still black at the edges.

Here is how my water looked before upgrading to UWS:
![2017-10-16_15-38-08](https://user-images.githubusercontent.com/10613340/31655247-98e5dfe6-b328-11e7-8da7-80e7722d8b3f.jpg)

Here is how the flashlight effect looks now.
![newwater](https://user-images.githubusercontent.com/10613340/31655134-390601e6-b328-11e7-8c3d-5e1d74167e06.PNG)

I'm lost on how to solve this.
Thanks in advance!

**Comment by MCPGNZ** [comment]
**solved by [@Tommily69](https://forum.unity.com/threads/ultimate-water-system-the-most-advanced-realtime-water-simulation.493984/page-5#post-3256706)**

**todo:** 
- [ ] Add the solution to the codebase

**Comment by MCPGNZ** [comment]
Added Common Issues section in documentation.
