### ISSUE TITLE
Charater phantom

### ISSUE THREAD

**Issue by LinShiXian** [Moonlit-Games/Ultimate-Water-System#14]
when the character into the water...
![image](https://user-images.githubusercontent.com/32889691/31699159-ff35b4f8-b3f3-11e7-9804-f63e825063c5.png) #

**Comment by LinShiXian** [comment]
**unity:** 2017.1.0f3
**uws version:** 1.0.0

**Comment by MCPGNZ** [comment]
Hi @LinShiXian 

Can you confirm that the problem still exists with the newest hot-fix and unity version
and if so could you describe how to replicate the problem?

**Comment by LinShiXian** [comment]
It seems if I open the planar reflections and stand around the water will happen~~

**Comment by MCPGNZ** [comment]
@LinShiXian 
In your _Water_ component, there is _Planar Reflections_ section, and there, you can use _Reflection Mask_ to decide, which layers will be reflected on water. Ensure that your character has a _Layer_ which is **_not_** selected in _Reflection Mask_ flags. 

I'm pretty sure that this was the problem (notify mi if it worked).

**Comment by MCPGNZ** [comment]
I do think that that was the problem, so I am closing the issue. If this was something different, please open a new issue and will try to find what is it.
