### ISSUE TITLE
Error when build.

### ISSUE THREAD

**Issue by LinShiXian** [Moonlit-Games/Ultimate-Water-System#15]
"Shader error in 'UltimateWater/Refraction/Collect Light': Internal error communicating with the shader compiler process"

**Comment by MCPGNZ** [comment]
Hi,

**[It seems that it is a Unity bug, you can read about it here](https://forum.unity.com/threads/build-error-shader-compiler-internal-error-compiling-shader-snippet-type-0-platform-5.404854/page-2).**

Is it happening after the project was imported? (Unity version, what hardware/software was used)
Did you tried to reimport the package/project?

**Comment by vageng** [comment]
Issue is still actual. with the last patch issues number increased, see screenshot below (unity version 5.6.4p1).
![shaderissue](https://user-images.githubusercontent.com/33422894/32443957-56f9773a-c31a-11e7-8faa-7a4f46616b5a.JPG)

**Comment by MCPGNZ** [comment]
It seem like the problems could be connected to Directx9. If you do not use DX9 (and you probably shouldn't, as it will soon be deprecated), you can:

* Go to the Edit->Project Settings->Player
* In the Other Settings tab, turn off the Auto Graphics APIs for Windows
* Click on Direct3D9 and remove it by clicking on the minus button.

**Comment by vageng** [comment]
Removing Directx9 support resolved the issue.
Thank you.

**Comment by MCPGNZ** [comment]
Added pragmas to remove the directx from CollectLight shader build.
