### ISSUE TITLE
Implementing ShipBowWaveEmitter and WaveEmitter

### ISSUE THREAD

**Issue by Bartolomeus755** [Moonlit-Games/Ultimate-Water-System#16]
Hello,

Would it be possible to implement the ShipBowWaveEmitter, WaveEmitter scripts and also the PlayWayWaterShip script from the Playway beta versions to Ultimate Water? That would make it easier to create realistic bow and stern waves and splashes at the same time.

This is my result with the PlayWay beta version. But I'm not able to create these bow and stern waves with Ultimate Water.
![atsboatsim](https://user-images.githubusercontent.com/28997692/31767222-8ab8f7fc-b4ca-11e7-8ae2-cb35ca8a91c1.jpg)

Regards
Marko

**Comment by MCPGNZ** [comment]
[Temporary solution provided by @Funkeys](https://forum.unity.com/threads/ultimate-water-system-the-most-advanced-realtime-water-simulation.493984/page-5#post-3260228)

**Comment by Bartolomeus755** [comment]
Awesome...thank you!

**Comment by MCPGNZ** [comment]
Added the emitters to the package.
