### ISSUE TITLE
"Disco effect" on AMD gpus

### ISSUE THREAD

**Issue by MCPGNZ** [Moonlit-Games/Ultimate-Water-System#18]
When using Planar Reflections on AMD cards, the "disco" colors appear.
Caused by Planar Reflection mip-mapping setting.

**unity:** -
**uws version:** 2.0.0b1
**spec:** amd cards 
**issued by:** @MCPGNZ

**Comment by leonidasos** [comment]
Awsome! 
Can you push it to hotfix-page?
