### ISSUE TITLE
Strange streaks in water with "Image Effect Deferred" when camera is e.g. 600 units above the water

### ISSUE THREAD

**Issue by mikeAmueller** [Moonlit-Games/Ultimate-Water-System#19]
Strange things happen with "Image Effect Deferred":

 When the camera is e.g. 600 units above the water I see strange streaks in the water.
 This effect does not occur with "Default Queue" and "Image Effect Forward".
 It seems to be a problem with the terrain - when I turn off the terrain, the stripes in the water are gone!
 Also an increase of the "Near Clipplane" of the main camera brings a certain improvement. However only with very high values, which are not really usable.
I have tested it also with a huge mesh-object in the water - the streaks are also there.

**unity:** 2017.1.0f3
**uws version:** 1.0.1 (no hot fixes) 
**spec:** Intel Core i7, Geforce GTX460
**issued by:** [@brave_mike](https://forum.unity.com/threads/ultimate-water-system-the-most-advanced-realtime-water-simulation.493984/page-6#post-3264610)

![pic1](https://user-images.githubusercontent.com/33066308/31955388-8620565a-b8e8-11e7-8c3a-90a60d5d1c49.jpg)
![pic2](https://user-images.githubusercontent.com/33066308/31955405-93fbf1f8-b8e8-11e7-8057-ce5a19b24ebb.jpg)
![pic3](https://user-images.githubusercontent.com/33066308/31955406-9586617a-b8e8-11e7-87c1-b49c4d9e2288.jpg)
![pic1](https://user-images.githubusercontent.com/33066308/31956064-99ac3ade-b8ea-11e7-8320-429ea3a84215.jpg)
![pic2](https://user-images.githubusercontent.com/33066308/31956487-e366dc6e-b8eb-11e7-84cf-6c00b5eefeb6.jpg)

**Comment by Funkeys** [comment]
Same here!
**unity:** 2017.2.0f3
**uws version:** 1.0.1 
**spec:** Intel Core i5, Geforce GTX970

I had the gray planes on the horizon (pic 3 from mike) in 2017.1.0f3 too, but they are gone in 2017.2.0f3 for me.
I just have the streaks on the horizon even when I turn off the terrain.

**Comment by MCPGNZ** [comment]
Solved in hot-fix 2.0.0b3
