### ISSUE TITLE
Submersion state not behaving correctly and Underwater IME component

### ISSUE THREAD

**Issue by SemihParlayan** [Moonlit-Games/Ultimate-Water-System#23]
Hello!
My camera submersion states are not working correctly. I've been testing with a very calm water, almost flat and it only switches to "NONE" when my camera is about 1 unit above the waterline. and when submerging the water into the water it takes about 0.5 units to switch to "PARTIAL" and then when the camera is almost 1-2 units under the water it switches to "FULL".
This also makes the Underwater IME component activate when the camera is actually above water.
When I watch the Underwater IME postprocess component in the Unity Profiler i takes up 20% of the GPU, this leads to my game losing 10-20 fps when under water.

I've also tried this in the sample scenes and the result is the same.
Thanks!

**unity:** 2017.1.0f3
**uws version:** 1.0.0 

EDIT
I also tried setting all the Underwater IME settings to low or off but it still takes 20% of the GPU.

EDIT 2
I just tried with the Water drop component to see if the water drop effects start occuring at the wrong moment as well... The water drops seems to work perfectly when the camera is submerged. I'm guessing that it is working because the Water drop s component does not use the Submersion state from the Water Camera component.

**Comment by pdq72** [comment]
I am having the same problem. After some initial testing, I have found that when my camera is above the water, even 2 units, the Underwater IME component is still enabled, there is a significant drop in performance  (game preview fps dropped 175 to 111). It took me a long time to figure out why my game is running slow while walking across an island terrain, where my first person camera was near water level such as walking along a beach. I believe this is the issue. When I completely remove the Underwater IME component together, performance is back to normal (albeit without UW effects)
Can anyone else confirm? Thanks.

unity: 2017.2.0f3
uws: 1.0.1 with hot_fix3

**Comment by SemihParlayan** [comment]
Hello Daniel Wojnarowski.
The reason this is causing problems in our game is that the player is supposed to float on the surface of the water when the character swims to the top of the water.
When the camera is not submerged but the character is in the water the player should float up and down with the waves and when the camera gets submerged the character no longer follows the waves.
I had this working via the submersionstate event but because as previously described the events are not called correctly and I can't implement bigger waves now which is a problem.

Thanks for reading and I hope you can find a fix for it as soon as possible.

**Comment by MCPGNZ** [comment]
The equation used for determining trigger points for submersion state change was 'quirky',
I've changed the equation to exactly match the camera near plane and added the Submersion tolerance parameter to the camera component to match given requirements.

**Comment by SemihParlayan** [comment]
Thank you!
How would I access this new update? Is there a hotfix available because I can't see any new update on Asset Store.

**Comment by MCPGNZ** [comment]
Hi!

The new version is already submitted to the Asset Store, after Unity approval it will be available for download.
