### ISSUE TITLE
Ocean (Fully featured) profile issue

### ISSUE THREAD

**Issue by vageng** [Moonlit-Games/Ultimate-Water-System#24]
In Ocean (Fully featured) profile Surface and Volume default shaders are missing. That is causing exception:
"Water in a scene doesn't contain necessary shaders to function properly. Please open this scene in editor and simply select the water to update its shaders". Hot fix patch is the latest one as of Nov-06-2017. Issue is a regression bug, missing in previous versions.

**Comment by MCPGNZ** [comment]
Hi @vageng 

Can you check if this solves the problem:

- go to the _Water component_
- click the _Edit_ button, located on the right side of the current _Shader Set_ setting
- check, if at the bottom of the opened scriptable object _Apply changes_ button is visible
    - if yes: click it
    - if no: click on the Surface Shaders foldout triangle, the button should appear

This should regenerate the shaders.
