### ISSUE TITLE
Water rendering issue with camera facing down

### ISSUE THREAD

**Issue by Stingo82** [Moonlit-Games/Ultimate-Water-System#25]
Not sure if this is UWS issue, but here it is:
When camera is high above water and facing down there is some rendering issue (see attached screenshots). I have reproduced it on UWS samples "Wake water" and "Open waters".
In "Open Waters" sample the same issue is in the "Scene" window.
![openwaters](https://user-images.githubusercontent.com/33510216/32611971-3149e334-c591-11e7-9ae1-1a1b080e5cc4.jpg)
"Wake Waters" sample:
![wakewater1](https://user-images.githubusercontent.com/33510216/32611972-31727d76-c591-11e7-953e-336e7a12a239.jpg)
In "Wake water" sample, if I set camera X rotation to 90 deg. I'm getting this error:
```
Assertion failed: Screen position out of view frustum (screen pos -1.#IND00, -1.#IND00) (Camera rect 0 0 617 454)
UnityEngine.Camera:ViewportPointToRay(Vector3)
UltimateWater.Utils.Math:RaycastPlane(Camera, Single, Vector3) (at Assets/Ultimate Water System/Scripts/Utilities/Math.cs:10)
UltimateWater.Internal.WaterRadialGrid:GetMatrix(Camera, Single) (at Assets/Ultimate Water System/Scripts/Geometry/WaterRadialGrid.cs:210)
UltimateWater.Internal.WaterRadialGrid:GetTransformedMeshes(Camera, Matrix4x4&, Int32, Boolean) (at Assets/Ultimate Water System/Scripts/Geometry/WaterRadialGrid.cs:61)
UltimateWater.Internal.WaterGeometry:GetTransformedMeshes(Camera, Matrix4x4&, WaterGeometryType, Boolean, Int32) (at Assets/Ultimate Water System/Scripts/Geometry/WaterGeometry.cs:123)
UltimateWater.WaterRenderer:Render(Camera, WaterGeometryType, CommandBuffer, Shader) (at Assets/Ultimate Water System/Scripts/WaterRenderer.cs:150)
UltimateWater.WaterCamera:RenderWaterWithShader(String, RenderTexture, Shader, Water) (at Assets/Ultimate Water System/Scripts/WaterCamera.cs:745)
UltimateWater.Internal.Foam:RenderOverlays(DynamicWaterCameraData) (at Assets/Ultimate Water System/Scripts/Foam.cs:122)
UltimateWater.DynamicWater:OnWaterRender(WaterCamera) (at Assets/Ultimate Water System/Scripts/DynamicWater.cs:242)
UltimateWater.Water:OnWaterRender(WaterCamera) (at Assets/Ultimate Water System/Scripts/Water.cs:753)
UltimateWater.WaterRenderer:RenderEffects(WaterCamera) (at Assets/Ultimate Water System/Scripts/WaterRenderer.cs:125)
UltimateWater.WaterCamera:RenderWaterEffects() (at Assets/Ultimate Water System/Scripts/WaterCamera.cs:836)
UltimateWater.WaterCamera:OnPreCull() (at Assets/Ultimate Water System/Scripts/WaterCamera.cs:554)
```
![wakewater2](https://user-images.githubusercontent.com/33510216/32611973-319b868a-c591-11e7-8686-7d531d21f438.jpg)

**unity:** 2017.2.0f3
**uws version:** 1.0.1 with and without hotfix b3 
**spec:** Intel Core i7, GTX 970 
**issued by:** [@Stingo]

**Comment by MCPGNZ** [comment]
I've located the problem and will add a fix for you shortly, (all the fixes combined will be available in the next Asset Store version submission)

**Comment by MCPGNZ** [comment]
I've solved the issue, the fix will be available in the next version release.
