### ISSUE TITLE
Water Profile Blending 

### ISSUE THREAD

**Issue by Bartolomeus755** [Moonlit-Games/Ultimate-Water-System#26]
Hello,

It would be nice to have only one slider for water profile blending, like the "WindSpeedSlider.cs" in PlayWay Beta versions of the water. This would be much easier to integrate.

Kind Regards
Marko

**Comment by MCPGNZ** [comment]
Added _WaterProfileBlendSimple_ that blends between two profiles using one blend factor.
(This will be available with the new version release on asset store)
