### ISSUE TITLE
Volume subtraction does not work as expected for box colliders with offset

### ISSUE THREAD

**Issue by Lohrion** [Moonlit-Games/Ultimate-Water-System#30]
Hello,

I tried setting up a terrain with volume subtraction, using a box collider. All of the issues noted below also occur in the reproduction project in the scene named MainMenuScene (password sent via PM on the Unity Forums): https://www.dropbox.com/s/sgyes3lu6peacm0/UWS%20Repro%20Project.zip?dl=0
I'm using Unity 5.6.1f1 and UWS 1.0.1 from the Asset Store. Deferred rendering path, linear color space, DX11.

a) I removed the default terrain collider and added a box collider, with changed offset and increased the size to contain the whole terrain. It seems the offset is not taken into account (it becomes clearer in the scene view than in the game view)
b) The water only appears in the game view once the game is started and I've switched to scene view and back
c) The water is not visible in a build
d) When adding a day/night-cycle, there seem to appear some white pixels on the water surface that do not seem to fit in. It could be coming from the reflection, but when adding a bloom effect these white pixels stay unaffected, while the expected reflections get bloomed. To show this I added UniStorm and Beautify to the project.

The reproduction project is a stripped down version of my main project, so please forgive any warnings about referenced scripts not being found. 

Thank you, 
Regards,
Patrick

**Comment by Lohrion** [comment]
Adding the box collider as a separate game object would be a workaround for a).

Though I just noticed another point, which can also be reproduced in the Volumes demo:
e) When moving the subtractive volume below the surface, the surface won't render anymore (e.g. for an underwater cave, there will be no more water on top of the cave).

**Comment by MCPGNZ** [comment]
I'm working on the mentioned issue:

- [x] WaterVolumeBase does not take colliders center into account
- [ ] Water appears only in after Scene was selected
- [ ] Water not visible in build
- [ ] Day/Night cycle white pixels 
- [ ] When moving the subtractive volume below the surface, the surface won't render anymore

**Comment by MCPGNZ** [comment]
@Lohrion  
I've also noticed, that the project that you've sent to me, does not have the latest hot-fix added 
[You can read how to download it here](https://github.com/Moonlit-Games/Ultimate-Water-System)

**Comment by MCPGNZ** [comment]
As for the **_(d)_**, are those white pixels result from the sun/moon? 
The _Smoothness_ parameter in the _Water Profile_ can help for that.
Does that solve your problem?

preview:
![smoothness 1](https://user-images.githubusercontent.com/8217782/33438741-f9afc1f8-d5eb-11e7-8e26-dd7ecd7cd561.png)
![smoothness 07](https://user-images.githubusercontent.com/8217782/33438742-f9cb4b8a-d5eb-11e7-8331-7b2162d5a13d.png)

**Comment by MCPGNZ** [comment]
I'm closing this one for now. If you still experience any issues please feel free to open another issue.
