### ISSUE TITLE
MissingReferenceException: The object of type 'Water' has been destroyed but you are trying to access it

### ISSUE THREAD

**Issue by stevenwanhk** [Moonlit-Games/Ultimate-Water-System#35]
UltimateWater.WaterSample.GetAndReset (at Assets/Ultimate Water System/SCript/Sectra/Samplng/WaterSample.cs:153)

Possible reason but not tested: I have a camera with Water Camera attached and the camera is DontDestroyOnLoad. When I change from one scene with Water to another scene without Water, this error keeps coming out.

**Comment by MCPGNZ** [comment]
Will look into it!

**Comment by MCPGNZ** [comment]
I've fixed it, it will be available in the new release (which will be send to Asset Store by the end of this week)
