### ISSUE TITLE
WaterCamera SubmersionStateChanged Event is not working

### ISSUE THREAD

**Issue by SemihParlayan** [Moonlit-Games/Ultimate-Water-System#36]
Hello!
I posted a previous issue almost two months ago and did not get any answers/solutions, I'm sorry to bother you again but I would really like a solution to this problem as this is causing some major problems in our game.

My camera submersion states are not working correctly. I've been testing with a very calm water, almost flat and it only switches to "NONE" when my camera is about 1 unit above the waterline. and when submerging the water into the water it takes about 0.5 units to switch to "PARTIAL" and then when the camera is almost 1-2 units under the water it switches to "FULL".
I've also tried this in the sample scenes and the result is the same.
Thanks!

**unity:** 2017.1.0f3
**uws version:** 1.0.0 

EDIT 
I just tried with the Water drop component to see if the water drop effects start occuring at the wrong moment as well... The water drops seems to work perfectly when the camera is submerged. I'm guessing that it is working because the Water drop s component does not use the Submersion state from the Water Camera component.

**Comment by MCPGNZ** [comment]
Hi, i am aware of this and will look into it after this weeks new release (sorry for the long waiting time)
I'm closing this issue as it's a duplicate. Can you provide details of how this bug is causing problems in your game (in the previous thread)

**Comment by SemihParlayan** [comment]
Hello, I have now provided more info about how it is causing a big problem in our game. Thanks and I’ll wait for you response.



________________________________
