### ISSUE TITLE
Deffered causes vertical lines on screen

### ISSUE THREAD

**Issue by MCPGNZ** [Moonlit-Games/Ultimate-Water-System#5]
With the Deferred rendering selected, the screen has dark vertical lines.

![upload_2017-10-15_13-49-26](https://user-images.githubusercontent.com/8217782/31620968-e2221ca0-b298-11e7-900c-b5ffa4d34a65.png)

**unity:**  2017.1.2p1
**uws version:** 1.0.0 
**spec:** windows 10
**issued by:** [@snacktime](https://forum.unity.com/threads/ultimate-water-system-the-most-advanced-realtime-water-simulation.493984/page-4#post-3254662)

**Comment by gamemachine** [comment]
This is windows 10 unity 2017.1 latest patch release.

**Comment by gamemachine** [comment]
btw noticed the horizontal lines are related to shadows.  setting directional light shadows to none and it goes away.

**Comment by MCPGNZ** [comment]
Hi @gamemachine 

Can you tell me if it's still a problem with the newest UWS hot-fix?
