### ISSUE TITLE
Shore foam black line

### ISSUE THREAD

**Issue by MCPGNZ** [Moonlit-Games/Ultimate-Water-System#9]
The black shore line artifact 

[video](https://youtu.be/YmxH8Yso4KU)
![zaeq09w 1](https://user-images.githubusercontent.com/8217782/31638728-6fcaadf6-b2d5-11e7-8ad4-928d51d15a19.png)

**unity:** -
**uws version:** 1.0.0 
**spec:** macOS,  AMD firepro D300
**issued by:** [@ftejada](https://forum.unity.com/threads/ultimate-water-system-the-most-advanced-realtime-water-simulation.493984/page-4#post-3253355) [@mons00n](https://forum.unity.com/threads/ultimate-water-system-the-most-advanced-realtime-water-simulation.493984/page-4#post-3255964)

**Comment by ftejada17** [comment]
hi @MCPGNZ 

I imagine you would see the other post I put in the UWS Unity forum regarding the parameter "EdgeBlendFactor" that may be what causes the problem.

I still put the video here in case you did not see it.

[https://youtu.be/cd85Bi1v9ls](url)

regards

**Comment by MCPGNZ** [comment]
I've replicated the problem and currently working on the solution.

**Comment by MCPGNZ** [comment]
Step-by-step hotfix for now:

#### 1 - UltimateWaterSystem/Modules/DepthModule.cs
add a line _after_ line 98
from:
```c#
_Commands.GetTemporaryRT(_WaterlessDepthId, width, height, depthBuffer, FilterMode.Point,
                _BlendedDepthFormat,
                RenderTextureReadWrite.Linear);
```
to:
```c#
_Commands.GetTemporaryRT(_WaterlessDepthId, width, height, depthBuffer, FilterMode.Point,
                _BlendedDepthFormat,
                RenderTextureReadWrite.Linear);
_Commands.ClearRenderTarget(true, true, Color.white);
```

#### 2 - UltimateWaterSystem/Shaders/Deferred/FinalColorMix.Shader
change the lines (126,127) 
from
```c#
half edgeBlendFactor = lerp(10.0, _EdgeBlendFactorInv, refractivity);
half blendEdgesFactor = saturate(edgeBlendFactor * (waterlessDepth - waterDepth));
```
to:
```c#
half edgeBlendFactor = _EdgeBlendFactorInv;
half blendEdgesFactor = saturate(0.6f * edgeBlendFactor * abs(waterlessDepth - waterDepth));
```

**Comment by MCPGNZ** [comment]
There still is a problem with color of the foam with deferred queue, so I'll close this Issue, after adding new one, describing problem mentioned.

**Comment by ftejada17** [comment]
Problem solved...

Thank you very much for the help.

Greetings.

**Comment by MCPGNZ** [comment]
Added to hotfix-b1
